/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2020 Neil C Smith.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 3 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 3 for more details.
 *
 * You should have received a copy of the GNU General Public License version 3
 * along with this work; if not, see http://www.gnu.org/licenses/
 *
 *
 * Please visit http://neilcsmith.net if you need additional information or
 * have any questions.
 */
package org.praxislive.ide.core.ui;

import java.util.Objects;
import javax.swing.JPanel;
import org.praxislive.ide.core.api.IDE;
import org.praxislive.ide.core.ui.spi.StartPagePanelProvider;

/**
 *
 */
public class VersionCheckStartPanel extends javax.swing.JPanel {

    /**
     * Creates new form DownloadStartPanel
     */
    public VersionCheckStartPanel() {
        initComponents();
        downloadButton.setVisible(false);
        currentVersionDisplay.setText(IDE.getVersion());
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentVersionLabel1 = new javax.swing.JLabel();
        currentVersionLabel = new javax.swing.JLabel();
        latestVersionLabel = new javax.swing.JLabel();
        currentVersionDisplay = new javax.swing.JLabel();
        latestVersionDisplay = new javax.swing.JLabel();
        downloadButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(currentVersionLabel1, org.openide.util.NbBundle.getMessage(VersionCheckStartPanel.class, "VersionCheckStartPanel.currentVersionLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(currentVersionLabel, org.openide.util.NbBundle.getMessage(VersionCheckStartPanel.class, "LBL_CurrentVersion")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(latestVersionLabel, org.openide.util.NbBundle.getMessage(VersionCheckStartPanel.class, "LBL_LatestVersion")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(latestVersionDisplay, org.openide.util.NbBundle.getMessage(VersionCheckStartPanel.class, "LBL_VersionChecking")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(downloadButton, org.openide.util.NbBundle.getMessage(VersionCheckStartPanel.class, "BTN_Download")); // NOI18N
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentVersionLabel)
                    .addComponent(latestVersionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(latestVersionDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(downloadButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentVersionDisplay)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentVersionLabel)
                    .addComponent(currentVersionDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latestVersionLabel)
                    .addComponent(latestVersionDisplay)
                    .addComponent(downloadButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        Utils.openExternalLink(Utils.DOWNLOAD_LINK);
    }//GEN-LAST:event_downloadButtonActionPerformed

    private boolean refresh() {
        String currentVersion = IDE.getVersion();
        String latestVersion = IDE.getLatestAvailableVersion();
        latestVersionDisplay.setText(latestVersion);
        downloadButton.setVisible(!Objects.equals(currentVersion, latestVersion));
        return true;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentVersionDisplay;
    private javax.swing.JLabel currentVersionLabel;
    private javax.swing.JLabel currentVersionLabel1;
    private javax.swing.JButton downloadButton;
    private javax.swing.JLabel latestVersionDisplay;
    private javax.swing.JLabel latestVersionLabel;
    // End of variables declaration//GEN-END:variables

    static class Provider implements StartPagePanelProvider {

        private final VersionCheckStartPanel panel = new VersionCheckStartPanel();

        @Override
        public String getTitle() {
            return null;
        }

        @Override
        public JPanel getPanel() {
            return panel;
        }

        @Override
        public boolean refresh() {
            return panel.refresh();
        }

    }

}
