/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2018 Neil C Smith.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 3 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 3 for more details.
 *
 * You should have received a copy of the GNU General Public License version 3
 * along with this work; if not, see http://www.gnu.org/licenses/
 *
 *
 * Please visit https://www.praxislive.org if you need additional information or
 * have any questions.
 */
package org.praxislive.ide.pxr;

/**
 *
 */
class BoundCodeResetPanel extends javax.swing.JPanel {

    BoundCodeResetPanel(boolean lastSavedAvailable) {
        initComponents();
        if (!lastSavedAvailable) {
            lastSavedOption.setEnabled(false);
            componentDefaultOption.setSelected(true);
        }
    }

    boolean isLastSavedOption() {
        return lastSavedOption.isSelected();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        lastSavedOption = new javax.swing.JRadioButton();
        componentDefaultOption = new javax.swing.JRadioButton();

        buttonGroup.add(lastSavedOption);
        lastSavedOption.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(lastSavedOption, org.openide.util.NbBundle.getMessage(BoundCodeResetPanel.class, "BoundCodeResetPanel.lastSavedOption.text")); // NOI18N

        buttonGroup.add(componentDefaultOption);
        org.openide.awt.Mnemonics.setLocalizedText(componentDefaultOption, org.openide.util.NbBundle.getMessage(BoundCodeResetPanel.class, "BoundCodeResetPanel.componentDefaultOption.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastSavedOption)
                    .addComponent(componentDefaultOption))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastSavedOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(componentDefaultOption)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton componentDefaultOption;
    private javax.swing.JRadioButton lastSavedOption;
    // End of variables declaration//GEN-END:variables
}
